AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Tutorial
Resources:
  HelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloLambda
      Handler: HelloLambda.lambda_handler
      Runtime: python2.7
      CodeUri: src
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        MyEndpoint:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  InvokeLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: InvokeLambda
      Handler: InvokeLambda.lambda_handler
      Runtime: python2.7
      CodeUri: src
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaFullAccess
      Events:
        MyEndpoint:
          Type: Api
          Properties:
            Path: /invoke
            Method: get
